import type { Handler } from "@netlify/functions";
import { createClient } from "@supabase/supabase-js";
import { Resend } from "resend";
import PDFDocument from "pdfkit";
import { validateSession } from "./lib/auth";
import { esc } from "./lib/html-escape";

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const resend = new Resend(process.env.RESEND_API_KEY!);

interface Message {
  role: "user" | "assistant";
  content: string;
}

function generatePdf(transcript: Message[], prospectEmail: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc
      .fontSize(20)
      .fillColor("#002A4E")
      .text("Workiva Scoping Transcript", { align: "center" });

    doc
      .moveDown(0.3)
      .fontSize(10)
      .fillColor("#686B70")
      .text("Harbor View Consulting", { align: "center" });

    doc
      .moveDown(0.2)
      .text(`Prospect: ${prospectEmail}`, { align: "center" });

    doc
      .moveDown(0.2)
      .text(`Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, { align: "center" });

    // Divider
    doc.moveDown(0.8);
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#D1D3D4")
      .stroke();
    doc.moveDown(0.8);

    // Messages
    for (const msg of transcript) {
      const isAssistant = msg.role === "assistant";
      const label = isAssistant ? "Harbor View" : "Prospect";
      const labelColor = isAssistant ? "#002A4E" : "#079FE0";

      doc.fontSize(9).fillColor(labelColor).text(label, { continued: false });
      doc
        .moveDown(0.2)
        .fontSize(10)
        .fillColor("#333333")
        .text(msg.content, { lineGap: 2 });
      doc.moveDown(0.6);

      // Add page break check
      if (doc.y > 700) {
        doc.addPage();
      }
    }

    // Footer
    doc.moveDown(1);
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#D1D3D4")
      .stroke();
    doc
      .moveDown(0.5)
      .fontSize(8)
      .fillColor("#686B70")
      .text("This transcript was generated by the Harbor View Consulting Workiva Scoping Agent.", { align: "center" });

    doc.end();
  });
}

export const handler: Handler = async (event) => {
  if (event.httpMethod !== "POST") {
    return { statusCode: 405, body: "Method Not Allowed" };
  }

  // Validate session
  const session = await validateSession(event, supabase);
  if (!session) {
    return { statusCode: 401, body: JSON.stringify({ error: "Unauthorized" }) };
  }

  // Use email from validated session
  const prospectEmail = session.email;

  let transcript: Message[], skipped: boolean;
  try {
    ({ transcript, skipped } = JSON.parse(event.body ?? "{}") as {
      transcript: Message[];
      skipped: boolean;
    });
  } catch {
    return { statusCode: 400, body: JSON.stringify({ error: "Invalid request body" }) };
  }

  if (!transcript?.length) {
    return { statusCode: 400, body: JSON.stringify({ error: "Missing transcript" }) };
  }

  const pdfBuffer = await generatePdf(transcript, prospectEmail);

  const date = new Date().toISOString().slice(0, 10);
  const pdfFilename = `workiva-scoping-transcript-${date}.pdf`;

  const escapedEmail = esc(prospectEmail);

  const subject = skipped
    ? `Workiva Scoping — Prospect skipped to scheduling (${prospectEmail})`
    : `Workiva Scoping Transcript — ${prospectEmail}`;

  const htmlBody = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8" /></head>
<body style="font-family: Lato, sans-serif; background: #F8F9FA; margin: 0; padding: 32px;">
  <div style="background: white; border-radius: 12px; padding: 32px; max-width: 600px; margin: 0 auto; border: 1px solid #D1D3D4;">
    <h2 style="color: #002A4E; margin: 0 0 8px;">Scoping Chat Transcript</h2>
    <p style="color: #686B70; margin: 0 0 16px; font-size: 14px;">
      ${skipped
        ? `The prospect (${escapedEmail}) skipped the scoping chat and went directly to meeting scheduling. A partial transcript is attached.`
        : `The scoping chat with ${escapedEmail} has been completed. Full transcript is attached as a PDF.`
      }
    </p>
    <p style="color: #686B70; font-size: 13px; margin: 0;">
      <strong style="color: #002A4E;">Messages:</strong> ${transcript.length}<br />
      <strong style="color: #002A4E;">Date:</strong> ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
    </p>
  </div>
</body>
</html>`;

  await resend.emails.send({
    from: process.env.RESEND_FROM_ADDRESS!,
    to: process.env.HV_NOTIFICATION_EMAIL!.split(",").map((e) => e.trim()),
    subject,
    html: htmlBody,
    attachments: [
      {
        filename: pdfFilename,
        content: pdfBuffer,
      },
    ],
  });

  return {
    statusCode: 200,
    body: JSON.stringify({ success: true }),
  };
};
